# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # TestFlight 배포 자동화
  lane :beta do
    increment_build_number(xcodeproj: "ToucheeseMVP.xcodeproj") # 빌드 넘버 증가
    build_app(scheme: "ToucheeseMVP")

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end

  # 앱심사 제출 자동화
  lane :release do
    version = get_version_number(xcodeproj: "ToucheeseMVP.xcodeproj")
    increment_build_number(xcodeproj: "ToucheeseMVP.xcodeproj") # 빌드 넘버 증가

    build_app(scheme: "ToucheeseMVP")

    upload_to_app_store(
      skip_metadata: false,
      skip_screenshots: true,
      submit_for_review: true
    )

  # 릴리즈 노트 반영
  changelog_update(version: version)

  end
end