# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # TestFlight 배포 자동화
  lane :beta do
    # 암호화된 파일 복호화(키는 .env 파일과 깃 시크릿에 보관)
    sh("openssl aes-256-cbc -pbkdf2 -d -in certs/ToucheeseDistribution.p12.enc -out certs/ToucheeseDistribution.p12 -k #{ENV['CERTIFICATION_KEY']}")
    sh("openssl aes-256-cbc -pbkdf2 -d -in certs/ToucheeseAppstoreConnect.mobileprovision.enc -out certs/ToucheeseAppstoreConnect.mobileprovision -k #{ENV['MOBILEPROVISION_KEY']}")
    sh("openssl aes-256-cbc -pbkdf2 -d -in certs/AuthKey_22N22888B2.p8.enc -out certs/AuthKey_22N22888B2.p8 -k #{ENV['AUTHKEY_KEY']}")

    sh("openssl aes-256-cbc -pbkdf2 -d -in fastlane/certs/GoogleService-Info.plist.enc -out ../ToucheeseMVP/Resources/GoogleService-Info.plist -k #{ENV['GOOGLESERVICE_KEY']}")
    sh("openssl aes-256-cbc -pbkdf2 -d -in fastlane/certs/Secrets.xcconfig.enc -out ../ToucheeseMVP/Resources/Secrets.xcconfig -k #{ENV['SECRET_KEY']}")

    install_provisioning_profile(
      path: "fastlane/certs/ToucheeseAppstoreConnect.mobileprovision"
    )

    create_keychain(
      name: "build.keychain",
      password: "fastlane",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    import_certificate(
      certificate_path: "fastlane/certs/ToucheeseDistribution.p12",
      certificate_password: ENV['CERTIFICATION_PASSWORD'],
      keychain_name: "build.keychain",
      keychain_password: "fastlane"
    )

    app_store_connect_api_key(
      key_id: ENV["KEY_ID"], # 앱 키 아이디
      issuer_id: ENV["ISSUER_ID"], # Issuer 아이디
      key_filepath: "./fastlane/certs/AuthKey_22N22888B2.p8", # .p8 키 파일 경로
      in_house: false # 큰 회사 같은 곳에서 로컬 서버 같은 환경에 쓰인다고 함
    )    

    latest = latest_testflight_build_number(
      app_identifier: "com.Toucheese.ToucheeseRelease"
    ).to_i

    # 빌드 넘버 증가
    increment_build_number(
      build_number: (latest + 1).to_s,
      xcodeproj: "ToucheeseMVP.xcodeproj"
    ) 

    build_app(
      scheme: "ToucheeseMVP",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.Toucheese.ToucheeseRelease" => "ToucheeseAppstoreConnect"
        }
      }
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: false,
      distribute_external: false,
      groups: ["FastRelease"]
    )

    sh("rm certs/ToucheeseDistribution.p12")
    sh("rm certs/ToucheeseAppstoreConnect.mobileprovision")
  end

  # 앱심사 제출 자동화
  lane :release do
    # 암호화된 파일 복호화(키는 .env 파일과 깃 시크릿에 보관)
    sh("openssl aes-256-cbc -pbkdf2 -d -in certs/ToucheeseDistribution.p12.enc -out certs/ToucheeseDistribution.p12 -k #{ENV['CERTIFICATION_KEY']}")
    sh("openssl aes-256-cbc -pbkdf2 -d -in certs/ToucheeseAppstoreConnect.mobileprovision.enc -out certs/ToucheeseAppstoreConnect.mobileprovision -k #{ENV['MOBILEPROVISION_KEY']}")
    sh("openssl aes-256-cbc -pbkdf2 -d -in certs/AuthKey_22N22888B2.p8.enc -out certs/AuthKey_22N22888B2.p8 -k #{ENV['AUTHKEY_KEY']}")

    sh("openssl aes-256-cbc -pbkdf2 -d -in fastlane/certs/GoogleService-Info.plist.enc -out ../ToucheeseMVP/Resources/GoogleService-Info.plist -k #{ENV['GOOGLESERVICE_KEY']}")
    sh("openssl aes-256-cbc -pbkdf2 -d -in fastlane/certs/Secrets.xcconfig.enc -out ../ToucheeseMVP/Resources/Secrets.xcconfig -k #{ENV['SECRET_KEY']}")

    install_provisioning_profile(
      path: "fastlane/certs/ToucheeseAppstoreConnect.mobileprovision"
    )

    create_keychain(
      name: "build.keychain",
      password: "fastlane",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )


    import_certificate(
      certificate_path: "fastlane/certs/ToucheeseDistribution.p12",
      certificate_password: ENV['CERTIFICATION_PASSWORD'],
      keychain_name: "build.keychain",
      keychain_password: "fastlane"
    )

    version = get_version_number(xcodeproj: "ToucheeseMVP.xcodeproj")

    app_store_connect_api_key(
      key_id: ENV["KEY_ID"], # 앱 키 아이디
      issuer_id: ENV["ISSUER_ID"], # Issuer 아이디
      key_filepath: "./fastlane/certs/AuthKey_22N22888B2.p8", # .p8 키 파일 경로
      in_house: false # 큰 회사 같은 곳에서 로컬 서버 같은 환경에 쓰인다고 함
    )    

    latest = latest_testflight_build_number(
      app_identifier: "com.Toucheese.ToucheeseRelease"
    ).to_i

    # 빌드 넘버 증가
    increment_build_number(
      build_number: (latest + 1).to_s,
      xcodeproj: "ToucheeseMVP.xcodeproj"
    ) 

    build_app(
      scheme: "ToucheeseMVP",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.Toucheese.ToucheeseRelease" => "ToucheeseAppstoreConnect"
        }
      }
    )

    upload_to_app_store(
      skip_metadata: false,
      skip_screenshots: true,
      submit_for_review: true
    )

    # 릴리즈 노트 반영
    changelog_update(version: version)

    sh("rm certs/ToucheeseDistribution.p12")
    sh("rm certs/ToucheeseAppstoreConnect.mobileprovision")
  end
end