name: iOS Deploy

# 시점을 정하는 조건
on:
  # PR이 닫힐 때 이벤트 발생
  pull_request:
    types: [closed]
    # 디벨롭이랑 메인 브랜치인 경우만
    branches:
      - develop
      - main

jobs:
  deploy:
    # 머지된 경우만 실행하도록 추가 조건
    if: github.event.pull_request.merged == true
    # 깃허브 액션의 가상 머신? 환경 설정 (iOS 빌드를 위해 필요하다고 함)
    runs-on: macos-14

    # 구체적인 설정 작업
    steps:
      # GitHub Actions가 리포지토리 코드를 다운로드
      - name: Checkout source code
        uses: actions/checkout@v3

      # Ruby 환경 세팅
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      # Bundle 세팅
      - name: Install dependencies
        run: |
          cd ToucheeseMVP
          bundle install

      # GitHub Secrets에 보안처리된 정보들 불러오기
      - name: Create API Key file from secret
        run: |
          cd ToucheeseMVP
          openssl aes-256-cbc -pbkdf2 -d -in fastlane/certs/ToucheeseDistribution.p12.enc -out fastlane/certs/ToucheeseDistribution.p12 -k "$CERTIFICATION_KEY"
          openssl aes-256-cbc -pbkdf2 -d -in fastlane/certs/ToucheeseAppstoreConnect.mobileprovision.enc -out fastlane/certs/ToucheeseAppstoreConnect.mobileprovision -k "$MOBILEPROVISION_KEY"
          openssl aes-256-cbc -pbkdf2 -d -in fastlane/certs/AuthKey_22N22888B2.p8.enc -out fastlane/certs/AuthKey_22N22888B2.p8 -k "$AUTHKEY_KEY"
        env:
          CERTIFICATION_KEY: ${{ secrets.CERTIFICATION_KEY }}
          MOBILEPROVISION_KEY: ${{ secrets.MOBILEPROVISION_KEY }}
          AUTHKEY_KEY: ${{ secrets.AUTHKEY_KEY }}
          
      # Fastlane 실행
      - name: Run Fastlane (beta or release)
        run: |
          cd ToucheeseMVP
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            bundle exec fastlane release
          elif [[ "${{ github.base_ref }}" == "develop" ]]; then
            bundle exec fastlane beta
          fi
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
          BUNDLE_GEMFILE: ./Gemfile
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          KEY_ID: ${{ secrets.KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
